# Regex patterns
patterns:
  confirmation_ok:
    - '(ok|okay|\+)'
    - '(так|да)'
    - 'вже (випив|випила|зробив|зробила)'
  pressure_prefix:
    - '^\s*(pressure|тиск)\b'
  health_prefix:
    - '^\s*(звіт|report|status)\b'

# Messages
messages:
  reminder:
    clarify: 'Не зрозуміла 🤔 Напишіть *так*, якщо вже виконали.'
    failed: 'Добре. Зараз попрошу медсестру прояснити.'
  nurse:
    clarification_failed: 'Пацієнт не підтвердив {event_name} після {attempts} запитів.'
  pressure:
    daily_reminder: 'Будь-ласка, виміряйте тиск і надішліть три числа (С/Д/ПБ).'

# Events
events:
  morning_med:
    retry_delay_seconds: 300
    main_text: 'Будь ласка, прийміть ранкові ліки 💊.'
    retry_text: 'Нагадування: ранкові ліки ще не прийняті 💊.'
    retries: 2
    escalate: true
  water:
    retry_delay_seconds: 180
    main_text: 'Випийте склянку води 🥤.'
    retry_text: 'Нагадую: випийте склянку води 🥤.'
    retries: 0
    escalate: false

# Timings
timings:
  clarify_delay_sec: 300
  clarify_retries: 2
  status_window_sec: 300
  pressure_remind_hour: 8
  log_msg_max: 250
  log_status_max_msgs: 10
