nurse_chat_id: 123456789
patterns:
  confirm_ok: "(?i)^(так|ok|\+|yes)$"
messages:
  nurse_alert: "❗ Пацієнт {chat_id} не відповів на нагадування «{event_key}»."
events:
  morning_med:
    schedule_time: "08:00"
    main: "Настав час ранкових ліків 💊"
    retry: "Нагадую про ранкові ліки."
    retry_delay: 600
    retries: 2
    clarify_retries: 2
timings:
  clarify_delay: 900
  bp_reminder_hour: 8
status_window_sec: 300
